version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql
    volumes:
      - urlDatabase-mysql-data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=urlDatabase
      - MYSQL_USER=salman
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
volumes: 
  urlDatabase-mysql-data: